export { default as Home } from './Home';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as Products} from './Products';
export { default as About} from './About';
export { default as Category} from './Category';
export { default as Wishlist} from './Wishlist';
export { default as Cart} from './Cart';
export { default as Productdetails} from './Productdetails';
export { default as  Checkout} from './Checkout';
export { default as  Contact} from './Contact';
export { default as PageNotFound} from './PageNotFound';
export { default as Account} from './Acount';